#!/bin/bash -e
set -x

whoami

export MAVEN_OPTS="-Xmx1024m"
export JAVA_OPTS="-Xms512m -Xmx2048m -XX:MaxPermSize=1024m"
export NEXUS_REPO_URL="https://artifact.intuit.com/nexus/content/repositories"

commit=$(git rev-parse HEAD)

function is_tag() {
   set +e
   v=$(git tag --points-at ${commit})
   if [ $? -ne 0 ]; then
      set -e
      echo "Unable to determine if this commit is a tag."
      exit 1
   elif [[ ${v} == "" ]]; then
      set -e
      return 1
   else
      set -e
      return 0
   fi
}

function get_version() {
    if is_tag; then
        echo "$(git tag --points-at ${commit})"
    else
        echo "${commit}"
    fi
}

# Define params based on whether this is a snapshot or Release build
# Make it case insensitive (master or Master)
if [ $GIT_BRANCH == master ] ; then

	echo "Running a Release build"

   	export VERSION_SRC_DIR=`dirname $0`
   	. $VERSION_SRC_DIR/build.properties
   	if [ -z $RELEASE_VERSION  ]; then
		echo "Make sure build.properties is present in the root directory\
 		of the git repo and contains value for variable RELEASE_VERSION"
		exit 1
	else
		num_digits=$(echo $RELEASE_VERSION | tr '.' '\n' | wc -l)
		if [ $num_digits != 3 ]; then
			echo "Give only three digits for variable RELEASE_VERSION, example 1.2.3"
			exit 1
		fi
	fi

	# To get ordered builds in Nexus yyyy-mm-dd format is used
	DATE=$(date +%Y-%m-%d)
	#FINAL_VERSION=$RELEASE_VERSION.$BUILD_NUMBER-$DATE
	export FINAL_VERSION=$RELEASE_VERSION.$BUILD_NUMBER
	echo "Building version $FINAL_VERSION"
   	find . -type f -name "pom.xml" -exec sed -i -e "s/1\.0-SNAPSHOT/${FINAL_VERSION}/g" {} +

   	export MVN_TARGETS="clean deploy"
   	export TargetGTGRepo=ENG.CTG.Intuit-Releases
   	export MVNPARAMS="-DskipTests=true -Dgit.branch=${GIT_BRANCH} -Drelease.version=${FINAL_VERSION} -Dsource.label=$GIT_COMMIT -Durl=$NEXUS_REPO_URL/$TargetGTGRepo/ -DaltDeploymentRepository=nexusserver::default::$NEXUS_REPO_URL/$TargetGTGRepo/ -Ddev.repo.url=$NEXUS_REPO_URL/$TargetGTGRepo/ -Drelease.repo.url=$NEXUS_REPO_URL/$TargetGTGRepo/ -DSTD_REPO_ID=nexusrelserver -Pnexusbuild"

   	# All maven commands in this script must use the -s option
   	export MAVEN_COMMAND="mvn -B -s settings-cicd.xml"

   	# build and publish/install to nexus app artifact (CI Build)
   	$MAVEN_COMMAND $MVN_TARGETS $MVNPARAMS
else
   	echo "Build is not configured for $GIT_BRANCH branch"
   	exit 0;
fi


